version: 2

## test sur la table clients
models:
  - name: clients
    description: "Table nettoyée des clients provenant de snp_clients"

    columns:
      - name: client_id
        description: "Identifiant client"
        tests:
          - not_null
          - unique

      - name: client_nom
        description: "Nom du client"
        tests:
          - not_null

## test sur la table commandes_details
  - name: commandes_details
    description: "Données nettoyées des détails de commande"

    columns:
      - name: commande_detail_id
        description: "Identifiant unique du détail de commande"
        tests:
          - not_null
          - unique

      - name: commande_id
        description: "Identifiant de la commande"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('commandes')
                field: commande_id

      - name: produit_id
        description: "Identifiant du produit"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('produits')
                field: produit_id

      - name: quantite
        description: "Quantité commandée"
        tests:
          - not_null
          - quantite_positive   # test custom

## les tests sur les commandes
  - name: commandes
    description: "Table nettoyée des commandes provenant de snp_commandes"

    columns:
      - name: commande_id
        description: "Identifiant unique de la commande"
        tests:
          - not_null
          - unique

      - name: client_id
        description: "Identifiant du client"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('clients')
                field: client_id

      - name: commande_date
        description: "Date de la commande"
        tests:
          - not_null

# les tests sur la table produits
  - name: produits
    description: "Table nettoyée des produits provenant de snp_produits"

    columns:
      - name: produit_id
        description: "Identifiant unique du produit"
        tests:
          - not_null
          - unique

      - name: produit_name
        description: "Nom du produit"
        tests:
          - not_null

      - name: categorie_id
        description: "Identifiant de la catégorie"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('categories_produits')
                field: categorie_id

      - name: unit_origin
        description: "Unité du produit"
        tests:
          - not_null

      - name: produit_prix
        description: "Prix du produit"
        tests:
          - not_null
          - price_positive
