version: 2

sources:
  - name: stg  # nom arbitraire pour ta source dans dbt
    database: DBT_DEMO
    schema: STAGING         # le schema réel dans PostgreSQL
    tables:
      - name: products
      - name: categories
      - name: customers
      - name: employees
      - name: order_details
      - name: orders
      - name: shippers
      - name: suppliers
